catalog:
  '@angular-eslint/eslint-plugin': ^21.2.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.7.1
  bumpp: ^10.4.1
  changelogithub: ^14.0.0
  citty: ^0.2.1
  consola: ^3.4.2
  find-up-simple: ^1.0.1
  nypm: ^0.6.5
  oxfmt: ^0.36.0
  oxlint: ^1.51.0
  oxlint-tsgolint: ^0.15.0
  tsdown: ^0.20.3
  typescript: ^5.9.3
  vitest: ^4.0.18

catalogMode: prefer

onlyBuiltDependencies:
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - cached-factory@0.1.0
  - ts-api-utils@2.2.0
  - undici-types@6.21.0
